pipeline {
    agent any

    stages {

        stage('Install dependencies backend') {
            steps {
                sh 'npm install --prefix back_pro_sec-main'
            }
        }

        stage('Build backend ') {
            steps {
                sh 'pwd'
                sh 'npm run build --prefix back_pro_sec-main'

            }
        }

    
        stage('Install Frontend Dependencies') {
            steps {
            cd front_proj_sec1-main
            rm -rf node_modules    
            npm cache clean --force 
            npm install              
                
            }
        }
        
        stage('build frontend '){
            steps {
                sh 'npm run build --prefix front_proj_sec1-main'
            }
        }

    }

}
