pipeline {
    agent any
  environment {
        REMOTE_HOST = '50.16.85.89'
        REMOTE_USER = 'ec2-user'
        SSH_CREDENTIALS = credentials('YOUR_SSH_CREDENTIALS_ID')

    }
    stages {
        stage('Install dependencies backend') {
            steps {
                sh 'npm install --prefix back_pro_sec-main'
            }
        }

        stage('Build backend ') {
            steps {
                sh 'npm run build --prefix back_pro_sec-main'
            }
        }

        stage('Install Frontend Dependencies') {
            steps {
                script {
                    dir('front_proj_sec1-main') {
                        sh 'rm -rf node_modules'
                        sh 'npm cache clean --force'
                        sh 'npm install'
                    }
                }
            }
        }
        
        stage('build frontend') {
            steps {
                dir('front_proj_sec1-main') {
                    sh 'npm run build'
                    }
            }
        }

        stage('Deploy to EC2') {
            steps {
                script {
                    def privateKey = env.SSH_PRIVATE_KEY

                    // Write private key to a temporary file
                    def sshKeyFile = writeFile file: 'temp_ssh_key', text: privateKey.trim()
                    sh "chmod 600 ${sshKeyFile}"

                    // Copy files to EC2 using SSH key
                    sshCommand remote: [
                        host: REMOTE_HOST,
                        user: REMOTE_USER,
                        keyFile: sshKeyFile,
                    ], command: "scp -i ${sshKeyFile} -r ./* ${REMOTE_USER}@${REMOTE_HOST}:~/"

                    // SSH into EC2 and start the application
                    sshCommand remote: [
                        host: REMOTE_HOST,
                        user: REMOTE_USER,
                        keyFile: sshKeyFile,
                    ], command: '''
                        cd ~/back_pro_sec-main
                        npm run build
                        npm start
                    '''
                }
            }
        }      
    }
}
