pipeline {
    agent any
  environment {
    REMOTE_HOST = '50.16.85.89'  // Name of the SSH server you configured in Jenkins
    REMOTE_USER = 'ec2-user'          // Name of the credential you added in Jenkins

    }
    stages {
        // stage('Install dependencies backend') {
        //     steps {
        //         sh 'npm install --prefix back_pro_sec-main'
        //     }
        // }

        // stage('Build backend ') {
        //     steps {
        //         sh 'npm run build --prefix back_pro_sec-main'
        //     }
        // }

        // stage('Install Frontend Dependencies') {
        //     steps {
        //         script {
        //             dir('front_proj_sec1-main') {
        //                 sh 'rm -rf node_modules'
        //                 sh 'npm cache clean --force'
        //                 sh 'npm install'
        //             }
        //         }
        //     }
        // }
        
        // stage('build frontend') {
        //     steps {
        //         dir('front_proj_sec1-main') {
        //             sh 'npm run build'
        //             }
        //     }
        // }

        stage('Deploy to EC2') {
            steps {
                script {
                    sh "chmod 600 back_pro_sec-main/servless.pem"
                    sh "cat back_pro_sec-main/servless.pem"    
                    // Copy files to EC2 using SCP
                    sh 'rm -rf back_pro_sec-main/node_modules'
                    sh 'rm -rf front_proj_sec1-main/node_modules'
                    sh "scp -o StrictHostKeyChecking=no -i back_pro_sec-main/servless.pem -r ./back_pro_sec-main ./front_proj_sec1-main ec2-user@50.16.85.89:~/"

                    // SSH into EC2 and execute build commands
                   
                
                    sh "ssh -o StrictHostKeyChecking=no -i back_pro_sec-main/servless.pem ec2-user@50.16.85.89 'cd ~/back_pro_sec-main && npm install && npm run build'"
                   
                }
            }
        }
}
}